### ISSUE TITLE
Bug: steam 사용 시 문장이 중복되는 문제

### ISSUE THREAD

**Issue by eunjios** [Si-gongan/sigongan-public-demo#22]
## 문제 상황
- stream을 사용하는 AI API 에 공통으로 발생하는 문제
- `AI 리포트 생성` 탭 클릭 후 다른 탭 클릭하고 다시 돌아오면 문장이 이상해짐 (ex. 안녕하안세녕요하세요)

## 문제 파악
- 위 경우 동일한 요청이 두 번 전송됨
- 즉 `streamReply` 가 병렬적으로 실행됨
- `setAnswer((prevReply) => prevReply + replyChunk);` 방식으로 state 변경하고 있음
- 동일한 stream 요청을 하지 못하게 막아야 함

## TODO
- [ ] 답변 생성 중일 때 중단하는 버튼 만들기
- [ ] 답변 재생성 버튼 만들기
- [ ] 답변 생성 중일 때 탭 버튼 비활성화
